version: '3.9'

services:
  frontend:
    volumes:
    - ./app-frontend:/app/src/

  monitoring:
    volumes:
    - ./app-monitoring:/app/src/

  api:
    volumes:
    - ./app-api:/app/src/
    environment:
      # Enables autoreload.
      APP_API_RELOAD: "True"
